### ISSUE TITLE
Show all clients (i.e. not only the top 10)

### ISSUE THREAD

**Issue by nine76evil** [sterrenburg/flutterhole#102]
Hello,

Love your app flutterhole and have a question regarding my VPN mullvad on Android. I have local traffic enabled but for some reason it blocks Flutterhole app but not anything else. Do you know how I can resolve this issue?

Thanks!

**Comment by sterrenburg** [comment]
Hello @nine76evil 👋 - Thanks for opening an issue!

I have heard from other users that they have issues with VPNs and SSL (perhaps #84 is similar).

Could you take a look at the API log page? Here you can see API requests from the app to your Pi-hole. You _should_ see some requests with e.g. `?summaryRaw=` which returns a 200 OK. If we can find out what requests are failing (e.g. timing out or returning a DNS error), we can take it from there.

**Comment by nine76evil** [comment]
This was my mistake from not entering the local IP. It's weird cause the laptop browser can find it using the domain name.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by nine76evil** [comment]
Anyway to get the app to show all active connections? Right now it only shows up to 10 with one being localhost?

Thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sterrenburg** [comment]
> This was my mistake from not entering the local IP. It's weird cause the laptop browser can find it using the domain name.

Glad to hear it! This happens to other people, including myself sometimes. I believe the phone's DNS service struggles to resolve pi.hole, you could always add it to your `hosts` file.

> Anyway to get the app to show all active connections? Right now it only shows up to 10 with one being localhost?

What do you mean exactly by "active connections"? If you mean multiple Pi-holes, you _should_ be able to add multiple.

**Comment by nine76evil** [comment]
No not multiple pi-holes..I have one Pi-Hole and like 20 connected devices but the app only shows 10 devices. I think maybe it's because the default on the web page is 10 with multiple pages. But there's no change to show all or next page option.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sterrenburg** [comment]
> No not multiple pi-holes..I have one Pi-Hole and like 20 connected devices but the app only shows 10 devices. I think maybe it's because the default on the web page is 10 with multiple pages. But there's no change to show all or next page option.

I think I know what you mean. Currently, the 10 clients are obtained using the Pi-hole API ast the `topClients` endpoint. I _believe_ this only returns up to 10 clients. I am not sure if it is possible to obtain _all_ clients.

Could you check out the output from the following URL in your browser (adjust as needed):

```
// {{ base_url  }}?topClients&auth={{ auth  }}
http://pi.hole/admin/api.php?topClients&auth=MY_TOKEN
```

You should get a list, mine is at most 10 items long. Could you share your results?

**Comment by nine76evil** [comment]
I'm sorry I don't follow what I'm supposed to do in the email you sent?

Sent from ProtonMail mobile

-------- Original Message --------
