### ISSUE TITLE
TLSV1_UNRECOGNIZED_NAME(tls_record.cc:587)

### ISSUE THREAD

**Issue by aljazzair** [sterrenburg/flutterhole#115]
**Describe the bug**

Hello and thank you for creating this application.

I cannot display dashboard for standard PiHole installation using FlutterHole over HTTPS with correct self signed certificates, using proper API credentials.
Tried to turn the "allow self signed certificates" option to no avail.

The same dashboard is accessible on any browser from the same device on the same network pointing to the same https URL.

**To Reproduce**
1. Go to 'https://10.11.11.10'
2. Tap on 'Dashboard'
3. See error

**Expected behavior**
Ability to access pihole dashboard over https

**Error Message**

Alice - HTTP Inspector
App name:  flutterhole
Package: sterrenburg.github.flutterhole
Version: v5.2.3
Build number: 641
Generated: 2020-08-29T11:57:54.150541

===========================================
Id: 681511586
============================================
--------------------------------------------
General data
--------------------------------------------
Server: 10.11.11.10
Method: GET
Endpoint: /admin/
Client: Dio
Duration 775 ms
Secured connection: true
Completed: true
--------------------------------------------
Request
--------------------------------------------
Request time: 2020-08-29 11:54:39.691907
Request content type: application/json; charset=utf-8
Request cookies: []
Request headers: {
"user-agent": "flutterhole"
}
Request size: 0 B
Request body: Body is empty
--------------------------------------------
Response
--------------------------------------------
Response time: 2020-08-29 11:54:40.466752
Response status: -1
Response size: 0 B
Response headers: null
Response body: Body is empty
--------------------------------------------
Error
--------------------------------------------
Error: DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error:
TLSV1_UNRECOGNIZED_NAME(tls_record.cc:587))
--------------------------------------------
Curl
--------------------------------------------
curl -X GET -H 'user-agent: flutterhole' 'https://10.11.11.10/admin/'
==============================================

**Versions (please complete the following information):**
 -  Pi-hole v5.1.2 Web Interface v5.1.1 FTL v5.2 

 - FlutterHole version: 5.2.3

**Additional context**
This is over VPN. 
Certificates created using pfsense. Works everywhere else with no issues.
I believe this is related to issue #84 possibly a duplicate?

**Comment by sterrenburg** [comment]
Hello @aljazzair  👋 - Thanks for opening an issue!

The error (`TLSV1_UNRECOGNIZED_NAME`) seems indeed similar to the issue you referenced. 

I will take a look at the SSL implementation of the app again ([this tiny snippet](https://github.com/sterrenburg/flutterhole/blob/27c34d6c3918d3fc5e2d6cee7444ead3e10005a8/lib/features/pihole_api/data/datasources/api_data_source_dio.dart#L44-L54)).

As an idea, have you tried turning _on_ the allowSelfSigned toggle, then _kill_ the app, then restart it? Perhaps the app's client instance is not updated correctly in the linked snippet.

**Comment by aljazzair** [comment]
Hello

Thank you very much for taking the time to review and answer.
I did follow your advice and it works. I am now able to open the application and view the dashboard on both my android devices :)
I am now closing this issue.
