### ISSUE TITLE
Query log of clients not loading

### ISSUE THREAD

**Issue by r3htanz** [sterrenburg/flutterhole#129]
**Describe the bug**
Query log of clients are not loading. The query log of all querys answered by pihole is loading, but a specific query log a client is not shown. It stucks at a loading screen. 

**To Reproduce**
1. Go to 'Clients'
2. Tap on a connected client
3. See error

**Expected behavior**
Showing the querys answered or blocked by pihole for a specific client. 

**Screenshots**
![Screenshot_2021-01-03-10-46-33-911_sterrenburg.github.flutterhole.jpg](https://user-images.githubusercontent.com/27449365/103476229-2aa76e80-4db4-11eb-897f-6f8d27f8e989.jpg)

**Versions (please complete the following information):**
 - Pi-hole version: 5.2.2
 - FlutterHole version: 5.2.3

**Additional context**
Using FlutterHole on a Xiaomi Mi 10 with Android 10.

**Comment by sterrenburg** [comment]
See #128 regarding hanging query logs
