### ISSUE TITLE
Compatibility with PiHole + AdGuardHome

### ISSUE THREAD

**Issue by yanniedog** [sterrenburg/flutterhole#130]
AdGuardHome is based on PiHole. 
Both are extremely similar projects, and AdGuardHome may soon be more popular than PiHole.

There is currently no way to selectively unblock traffic from AdGuardHome on Android.

It is only a small extension of your project to interact with both AdGuardHome in addition to PiHole.

You would open yourself up to thousands and thousands of additional users if you offered compatibility with AdGuardHome.

Please consider.

**Comment by sterrenburg** [comment]
Hello @yanniedog 👋 - Thanks for opening an issue!

I have no experience with AdGuardHome, but it seems the API is not based on the Pi-hole API. Seems more like a separate project to me, unless there's an existing API/someone is making one.
