### ISSUE TITLE
Pi-hole appears to be paused every time Flutterhole is opened, regardless of whether or not it is actually paused 

### ISSUE THREAD

**Issue by jdrch** [sterrenburg/flutterhole#158]
**Describe the bug**
The amber "paused" icon appears every time Flutterhole is opened on Android. 

**To Reproduce**
1. Open Flutterhole 

**Expected behavior**
Flutterhole shows actual current status of Pi-hole. 

**Screenshots**

**Versions (please complete the following information):**
 - Pi-hole version: latest stable version 
 - FlutterHole version: 5.2.3

**Additional context**

**Comment by dimondeg** [comment]
I have the same problem.  Clearing cache and files didn't help.  As well as reinstalling the app. Trivial but (don't underestimate the power of the reboot :)) rebooting the pihole and the phone didn't lead to success.  Pihole itself works fine and is active.

**Comment by dimondeg** [comment]
Pihole and the app are up to date. Hope there will be a solution soon.  Thanks in advance.

**Comment by sterrenburg** [comment]
Sorry to hear that. Anecdotally, my own Pi-hole is currently only reporting it is "disabled", even if the Web interface is showing it's enabled.

Could you take a look at the API response of the status endpoint, while it is enabled and disabled, at:
http://pi.hole/admin/api.php?status
(replace `pi.hole` with your own local IP if needed)

The status should show as "enabled" or "disabled". Does this URL show you the correct status, in line with the web interface?

**Comment by sanjeev40084** [comment]
@sterrenburg in my case even though the actual status was enabled, the endpoint showed 'disabled'.

**Comment by dimondeg** [comment]
Hello and thanks for quick reply.  In fact, the status shows disabled.  Do you have a hint where I can correct it in pihole. 
 Thanks in advance.

**Comment by jdrch** [comment]
> Hello and thanks for quick reply.  In fact, the status shows disabled.  Do you have a hint where I can correct it in pihole. 
>  Thanks in advance.

My guess would be this is a bug we'd have to report in the Pi-hole project itself.

**Comment by sanjeev40084** [comment]
> > Hello and thanks for quick reply.  In fact, the status shows disabled.  Do you have a hint where I can correct it in pihole.
> > Thanks in advance.
> 
> My guess would be this is a bug we'd have to report in the Pi-hole project itself.

reported bug in pihole github site: https://github.com/pi-hole/pi-hole/issues/4572

**Comment by sanjeev40084** [comment]
it looks like the issue has already been fixed. whenever there is new release, i believe this issue will be fixed. https://github.com/pi-hole/AdminLTE/pull/2052

**Comment by jdrch** [comment]
@sanjeev40084 Thanks for the follow up!

**Comment by sterrenburg** [comment]
> it looks like the issue has already been fixed. whenever there is new release, i believe this issue will be fixed. [pi-hole/AdminLTE#2052](https://github.com/pi-hole/AdminLTE/pull/2052)

Glad to hear it! I assume the issue will be resolved once the patch is available.

**Comment by Anoni-Mouse** [comment]
> Sorry to hear that. Anecdotally, my own Pi-hole is currently only reporting it is "disabled", even if the Web interface is showing it's enabled.
> 
> Could you take a look at the API response of the status endpoint, while it is enabled and disabled, at:
> http://pi.hole/admin/api.php?status
> (replace `pi.hole` with your own local IP if needed)
> 
> The status should show as "enabled" or "disabled". Does this URL show you the correct status, in line with the web interface?

Mine shows Disabled. I'm on Android 10 on Samsung Note 9

**Comment by jdrch** [comment]
> I'm on Android 10 on Samsung Note 9

🤝

**Comment by jdrch** [comment]
Can confirm the issue is fixed. Latest Pi-hole running on Debian 11.2; Flutterhole on Android 10 on Samsung Galaxy Note9.
