### ISSUE TITLE
Logs no longer accessible

### ISSUE THREAD

**Issue by Scarletvye** [sterrenburg/flutterhole#159]
**Describe the bug**
After updating Pi.Hole to the latest version, the app no longer displays logs. There is only a loading symbol. 

**To Reproduce**
1. Open app
2. Select 'Query log' 
3. Nothing happens

**Expected behavior**
I would expect to see requests being redirected to port 53 or being blocked. 

**Versions (please complete the following information):**
 - Pi-hole version: 5.10
 - FlutterHole version: 5.2.3

**Additional context**
I have refreshed my Pi-hole instalation.
Used a different nginx config. 
Pi-hole diagnostics report no errors.
Web UI is fully functional.

**Comment by Scarletvye** [comment]
Update: This might be fixed soon.
Source: https://github.com/pi-hole/AdminLTE/issues/2178

**Comment by Aura-Bella-Fiora** [comment]
You can fix ist yourself for now.
Edit on the pihole the file /var/www/html/admin/api_FTL.php and write under the first line that contains "<?php" the following: 
header('Content-type: application/json');

The app is now working for me with this

**Comment by Scarletvye** [comment]
> You can fix it yourself for now. Edit on the pihole the file /var/www/html/admin/api_FTL.php and write under the first line that contains "<?php" the following: header('Content-type: application/json');
> 
> The app is now working for me with this

Can confirm this is a valid fix.
