### ISSUE TITLE
Reverse proxy settings 

### ISSUE THREAD

**Issue by modem7** [sterrenburg/flutterhole#42]
There needs to be a function to obscure reverse proxy basic http auth details so that they're not located in plain text

It currently works with https://user:pass@domain.com, but this is quite an insecure method of inputting these values

**Comment by sterrenburg** [comment]
The http engine might be replaced by dio, implementing proxies with obscured fields sounds doable: https://github.com/flutterchina/dio#using-proxy

**Comment by oakkitten** [comment]
i'm not sure what it looked like in the previous versions, but doesn't this add a forward proxy instead of the regular basic auth?

**Comment by modem7** [comment]
My initial post is incorrect. @oakkitten made a very good point in https://github.com/sterrenburg/flutterhole/issues/49#issuecomment-517665591

Instead of: "It currently works with https://user:pass@domain.com, but this is quite an insecure method of inputting these values"

It should be: It currently works with https://user:pass@domain.com, but having this in plaintext is quite an insecure method of showing these values.
