### ISSUE TITLE
API token is empty

### ISSUE THREAD

**Issue by ricktendo** [sterrenburg/flutterhole#47]
Just updated to v2.1.29+360 and the Pihole settings are not getting saved, Configuration name, Host, API token etc. none of my configurations are recorded.
I make changes & hit save, I go to the dashboard and see error "API token is empty," after I return to Settings I see all my changes are gone.

I tried clearing app cache and storage folders, this does not help.

**Comment by scorrigan** [comment]
I am having the exact same issue.

**Comment by sterrenburg** [comment]
Hi, my apologies. I have received multiple reports on this, so I will work on it as soon as I can!

Unti then, the previous release build should still be available on F-droid.

**Comment by sterrenburg** [comment]
A new version is now available on Google Play, please update to 2.1.30+ and let me know if you still experience any issues.

**Comment by ricktendo** [comment]
Now works perfectly

Great job, love the new update!!!
