### ISSUE TITLE
Update pihole  threw the app

### ISSUE THREAD

**Issue by JakobHeubl** [sterrenburg/flutterhole#51]
It would be nice to see the current version of the pihole and updating the pihole if needed.
This would be nice too for adding or changing the current added block lists.

**Comment by sterrenburg** [comment]
Hi, currently you can see some versions in the Health Check tab on the configuration edit screen. Is this what you're looking for?

You cannot update the Pihole from the app, sounds like a good feature! Same for managing blocklists.

**Comment by JakobHeubl** [comment]
Hey, no, actually I was not looking for something! 
I am actually quite impressed with your app and I only wanted to contribute to this impressive work.
So thanks for responding to me and trying to help.

**Comment by JakobHeubl** [comment]
Short follow up question.
Where do you put this function? I can not find it in the app.

**Comment by sterrenburg** [comment]
Hi, I made some new issues for the features you suggested (#57 and #58). Due to some blocking issues, they are labeled 'future feature' for now.

**Comment by JakobHeubl** [comment]
Okay thanks
