### ISSUE TITLE
Suggestion: Follow System Dark Mode

### ISSUE THREAD

**Issue by cgorlla** [sterrenburg/flutterhole#55]
It would be nice if there was an option to have dark mode activate when the system is in dark mode.

**Comment by sterrenburg** [comment]
Currently the app user the dynamic_theme package. It has [an open issue](https://github.com/Norbert515/dynamic_theme/issues/21) regarding your suggestion.

**Comment by transf** [comment]
Sounds good, thanks for your work on this great project Tom. Will close for now.
