### ISSUE TITLE
Make API key optionally visible

### ISSUE THREAD

**Issue by jdrch** [sterrenburg/flutterhole#65]
Requesting that an option be added to make the API key visible. This would help tremendously for [bugs like this](https://github.com/sterrenburg/flutterhole/issues/60), in which the app was broken because of a space added to the end of the key by Pi-hole itself. If the key had been visible, this problem would have been immediately solvable.

**Comment by sterrenburg** [comment]
API token field is now toggleable. Also many trims were added to prevent future headaches.
