### ISSUE TITLE
Client dio error: null

### ISSUE THREAD

**Issue by dannytsang** [sterrenburg/flutterhole#66]
I'm unable to connect to my PiHole with the error below. When I go to the /admin/api.php page from my browser it shows a JSON response for what looks like dashboard data.

App version: v2.1.4+479
OS: Android 10
Build: QQ1A.191205.008
Hardware: Pixel 3

Error log:
`(2019-12-29 21:23:04.672709: client	dio error:	 null, 2019-12-29 21:22:59.355600: client	request:	 http://<mydndns>:8081/admin/api.php?status=, 2019-12-29 21:20:05.500768: client	dio error:	 null, ..., 2019-12-29 21:19:22.902399: client	request:	 http://<mydndns>:8081/admin/api.php?summaryRaw=, 2019-12-29 21:19:22.885183: main	_runMainZoned.<ac>.<ac>:	 Running in release mode)`

**Comment by sterrenburg** [comment]
Hello, the new V5 version should provide you with better feedback for your Pi-hole. If you are still interested, check out the new builds! Beware that the app now supports Pi-hole V5.
