### ISSUE TITLE
Pihole beta 5 

### ISSUE THREAD

**Issue by JBakers** [sterrenburg/flutterhole#69]
The beta5 broke the Dashboard/summary page.
Clients and domain pages continue to work.

**Comment by Schnuecks** [comment]
Same here with the beta

**Comment by jdrch** [comment]
Yeah please get this fixed so at least it's working by the time 5.0 is released.

**Comment by biship** [comment]
Please fix

**Comment by jdrch** [comment]
Welp, still not fixed despite 5.0's release, *but* based on 5.0's release notes it seems all apps that interact with Pi-hole's inner functionality basically need to be rewritten due the app's transition to a database backend. At least the Enable/Disable toggle works.

**Comment by sterrenburg** [comment]
I noticed the Pihole 5.0 release as well! Will try and make a release that works for the new version.

**Comment by peatrick** [comment]
> I noticed the Pihole 5.0 release as well! Will try and make a release that works for the new version.

Awesome, thanks, sir! Will be seriously looking forward to this update if you can make it work. Appreciate your continued efforts.

**Comment by sterrenburg** [comment]
Since releases on the Play Store currently have a long expected delay, I just created a pre-release of the 5.0.0 build. It contains a fat APK that is _not_ verified. The only guarantee I will give is that it works on my machine. :)

I expect to slowly start deploying to the closed alpha and open beta on the Play Store again. Some features are missing compared to previous versions, so be doubly warned of unstable releases!

**Comment by Anoni-Mouse** [comment]
> The beta5 broke the Dashboard/summary page.
> Clients and domain pages continue to work.

I have pihole 5 installed and since then the app doesn't work. I removed it then reinstalled it but when I open it I only get a black screen

**Comment by jdrch** [comment]
> 
> 
> > The beta5 broke the Dashboard/summary page.
> > Clients and domain pages continue to work.
> 
> I have pihole 5 installed and since then the app doesn't work. I removed it then reinstalled it but when I open it I only get a black screen

Enable/Disable (The Play/Pause button at the top right of the main window) should still work. Or at least it does on my Note9 running Android 10.

**Comment by Anoni-Mouse** [comment]
I also have Note 9 with Android 10, but since I removed the app and reinstalled it, I see nothing at all, just black screen!
________________________________

**Comment by jdrch** [comment]
🤔

**Comment by Anoni-Mouse** [comment]
I solved the issue, I had to go to app settings and flush data. For some reason un installing the app didn't remove the data.
________________________________

**Comment by jdrch** [comment]
@Anoni-Mouse Did clearing data get the entire app working again, or just the enable/disable toggle?

Also it might be a good idea to edit your comment to remove our GitHub auth codes that somehow got dumped into it via the email reply ...

**Comment by Schnuecks** [comment]
Looks good so far, i must uninstall the prvious one and install the alpha. Then i got the dashboard with authentication erros, re-entered the api code, restart the app and now all is there. only problem is that my dns resolvers is shown as null. because i use custom upstream servers.

**Comment by Anoni-Mouse** [comment]
> @Anoni-Mouse Did clearing data get the entire app working again, or just the enable/disable toggle?
> 
> Also it might be a good idea to edit your comment to remove our GitHub auth codes that somehow got dumped into it via the email reply ...
> 
> I just contacted GitHub about that as there's no way that content should have made it into the actual comment.

Thanks pal. It was because I replied directly from my email. Thanks for bringing this to my attention. 

Well, after I upgraded to Pihole 5, the app showed blank content on my dashboard, so one of the things I tried to do was to uninstall the app, and try to install it back. When I open the app, it just gave be black screen no matter how long I waited. I had this idea that the uninstall might not have cleaned everything so from the newly installed app, I went to Android App in settings, and saw that there were 200 MB of app data/cache, so I cleared everything and opened the app successfully. But I also had to reconfigure all the app settings. I got it working, but the problem of the dashboard still persist, i.e., a blank view. All the other settings and windows seem to work fine

**Comment by sterrenburg** [comment]
For anyone wanting to try out the signed alpha builds for version 5, you can join the closed alpha on Google Play here: https://play.google.com/apps/testing/sterrenburg.github.flutterhole.

**Comment by Schnuecks** [comment]
this beta version keeps complete blank. the alpha from the assets works fine. the beta is versioned with 2.1.4. i think i must wait if available via play store?

**Comment by ryanjmchale** [comment]
I'm assuming the beta requires updating on the play store as its still the October build.

**Comment by biship** [comment]
That link signed me up for the beta version, which is the Oct 2019 build.

**Comment by tjeffree** [comment]
> I'm assuming the beta requires updating on the play store as its still the October build.

> That link signed me up for the beta version, which is the Oct 2019 build.

@sterrenburg says above:
> I expect to slowly start deploying to the closed alpha and open beta on the Play Store again. Some features are missing compared to previous versions, so be doubly warned of unstable releases!

So I think patience is key here.

**Comment by sterrenburg** [comment]
A beta version is now available on the Play Store beta. 

If you are interested in beta testing, you can join via https://play.google.com/apps/testing/sterrenburg.github.flutterhole.

**Comment by Anoni-Mouse** [comment]
I get the email about Beta Testing, and I became a beta tester, yet I see no beta version in the store

**Comment by sterrenburg** [comment]
> I get the email about Beta Testing, and I became a beta tester, yet I see no beta version in the store

@Anoni-Mouse don't quote me on this, but I believe the beta rollout takes some time to propagate to all regions. Please check again in a few hours, if it still doesn't show up, I will look into it!

**Comment by Anoni-Mouse** [comment]
Woooohooo, I finally got the beta and it is working! Thanks

**Comment by jdrch** [comment]
> 
> 
> Looks good so far, i must uninstall the prvious one and install the alpha. Then i got the dashboard with authentication erros, re-entered the api code, restart the app and now all is there. only problem is that my dns resolvers is shown as null. because i use custom upstream servers.

@sterrenburg Is a complete reinstall necessary for full functionality? I got the beta build and plots are down but the number totals at the top are there.

**Comment by Anoni-Mouse** [comment]
Ok so here are the latest updates regarding this great project. If I update Flutterhole beta over the existing version, I get errors even if the configuration is correct (cannot see queries, white/black lists). I had to completely uninstall the app, install the beta version and for security I have flushed the beta version data. Then I entered all the required settings and everything is working like a charm!

**Comment by gorillap** [comment]
My interface was also broken after the 5.0 update.
I cleared date, deleted.my pihole and set it up again.
Instead of using the default info, I entered http://192.168.1.xxx (direct IP address) and pasted the API.key and everything populated normally on all pages....
Except for the primary reason that I used this app...
The live query log is still not showing

**Comment by jdrch** [comment]
> 
> 
> Ok so here are the latest updates regarding this great project. If I update Flutterhole beta over the existing version, I get errors even if the configuration is correct (cannot see queries, white/black lists). I had to completely uninstall the app, install the beta version and for security I have flushed the beta version data. Then I entered all the required settings and everything is working like a charm!

I guess that makes sense given the Pi-hole's database backend change. Thanks. Created an [issue](https://github.com/jdrch/Hardware/issues/154) for it on my end.

**Comment by gorillap** [comment]
I cleared data and re-configured as well as uninstall and reinstall/reconfigure.
I'm able to get basic general stats, but still no live query log with option to whitelist/blacklist domains which is my primary reason for using this application.

**Comment by biship** [comment]
I can't even connect to my pihole from the app. hostname, port & api are fine. No idea why not.

**Comment by jdrch** [comment]
@biship  There might be a trailing space in your API key. Delete the last character in the field for it in Flutterhole and see if that works.

**Comment by biship** [comment]
No trailing space.
I am using nginx with a password, which I can't enter in the app.
So I wonder if the app gets the login page and fails.

**Comment by Anoni-Mouse** [comment]
Here are some screenshots of what I see. The UI has been changed a bit and logging is seen if you click the zZZ icon
![20200517_025830](https://user-images.githubusercontent.com/39582133/82133343-67a1ff00-97eb-11ea-98b3-1602ff84dff4.jpg)
![20200517_030422](https://user-images.githubusercontent.com/39582133/82133344-74265780-97eb-11ea-8373-3a52f9725d46.jpg)
![20200517_030155](https://user-images.githubusercontent.com/39582133/82133348-7b4d6580-97eb-11ea-8775-69f9a89a2a33.jpg)
![20200517_025901](https://user-images.githubusercontent.com/39582133/82133354-86a09100-97eb-11ea-8f1c-948f028ad845.jpg)
![20200517_025932](https://user-images.githubusercontent.com/39582133/82133357-8f916280-97eb-11ea-844e-5c78df40b9be.jpg)
![20200517_030043](https://user-images.githubusercontent.com/39582133/82133362-9b7d2480-97eb-11ea-8494-26da28edc017.jpg)

**Comment by gorillap** [comment]
That has not helped.
The "zzz" button does what it is supposed to do and brings up and option to pause/sleep
![Screenshot_20200517-042402](https://user-images.githubusercontent.com/12369968/82140694-42ff5480-97f6-11ea-9c1a-0d3589e511ee.jpg)

**Comment by gorillap** [comment]
![Screenshot_20200517-042459](https://user-images.githubusercontent.com/12369968/82140714-632f1380-97f6-11ea-9e00-db4afdfdae44.jpg)

**Comment by sstolk90** [comment]
Also in the pie charts of the forward destinations the numbers are not matching the colors in the legenda.

**Comment by gorillap** [comment]
There is no general/universal/network log visible.
Selecting each device individually shows the query log for that specific device , but there is no ability to whitelist/blocklist from that list.

**Comment by sstolk90** [comment]
![Screenshot_20200517-112214__01](https://user-images.githubusercontent.com/65487781/82140749-49f78880-9831-11ea-9a87-c43cb84b347f.jpg)

**Comment by sterrenburg** [comment]
> @biship There might be a trailing space in your API key. Delete the last character in the field for it in Flutterhole and see if that works.

Regarding whitespace in API tokens: this _should_ be working properly now, since we trim the input string after scanning the QR code. This lead to some issues in previous versions too.

> Also in the pie charts of the forward destinations the numbers are not matching the colors in the legenda.

This was a bug, and the fix will be in the upcoming release.

> There is no general/universal/network log visible.
Selecting each device individually shows the query log for that specific device , but there is no ability to whitelist/blocklist from that list.

The **API Log** page contains all HTTP requests that the app sent out. This is more for my own debugging purposes, but it might be insightful to see what kind of requests you are sending. 

Try looking for requests with a query parameter `disable=<time_in_seconds>`; are any of these requests sent? Do they contain an `auth` parameter? Issue #77 also has some issues regarding the API token, take a look there too.

**Comment by timocapa** [comment]
My PiHole isn't password protected, so I can't grab the API Key

The dashboard doesn't work and complains about being unauthenticated despite authentication not being required I believe

**Comment by sterrenburg** [comment]
> My PiHole isn't password protected, so I can't grab the API Key
> 
> The dashboard doesn't work and complains about being unauthenticated despite authentication not being required I believe

@timocapa that is correct, the app breaks with a Pi-hole that is not password protected. please check #79 for progress!

**Comment by timocapa** [comment]
Ah, I apologize, I didn't see that. :)

**Comment by jdrch** [comment]
OK, got everything up and running, thanks @sterrenburg for the quick fix and thanks @Anoni-Mouse + @biship for the details.

1 minor warning: be sure to allow the app to autodetect your Pi-hole instance 1st, then edit that instance in the settings with your API key, etc. If you try to create a standalone entry from scratch you'll wind up with 2 Pi-hole entries in the settings and deleting one of them deletes both.

**Comment by jdrch** [comment]
> My PiHole isn't password protected, so I can't grab the API Key

Add a password, then allow others to toggle it if needed (I'm assuming allowing other people to turn it on or off is why you're not using a password) using the API key + Flutterhole as well Remote Switch for Pi-hole on Firefox and Chrome.

**Comment by gorillap** [comment]
> 
> 
> > There is no general/universal/network log visible.
> > Selecting each device individually shows the query log for that specific device , but there is no ability to whitelist/blocklist from that list.
> 
> The **API Log** page contains all HTTP requests that the app sent out. This is more for my own debugging purposes, but it might be insightful to see what kind of requests you are sending.
> 
> Try looking for requests with a query parameter `disable=<time_in_seconds>`; are any of these requests sent? Do they contain an `auth` parameter? Issue #77 also has some issues regarding the API token, take a look there too.

The API log shows no DNS queries, only 
GET /admin/api.php 55ms
GET /admin/api.php 65ms
GET /admin/api.php 67ms
GET /admin/api.php 121ms



This still doesn't touch on the primary issue.
There has always been a selectable "Query log" that shows a realtime view of all queries on the network passing through the PiHole. From there, you could always select them to blacklist or whitelist in realtime as well. It was an interface into the "query log" that is in the PiHole web interface.
This is no longer available. The only thing close it clicking on each individual device and seeing those queries, but even from those, there is no option to whitelist or blacklist domains being queried.

**Comment by sterrenburg** [comment]
@gorrilap The dedicated Query Log page is on top of my priority list, so this should find its way into an upcoming build. 

Regarding black/whitelists I am at a stand still, please check out issue #76. The endpoints from V4 broke and I haven't found a working solution for V5 yet.

**Comment by gorillap** [comment]
Awesome, than you very much for all your work on this.

**Comment by gorillap** [comment]
Perhaps a temporary workaround could be to just open the query log via
webview within the app. Obviously people can just save a bookmark on the
mobile desktop to this link, but this might be an easy workaround until the
issue is resolved.

http://192.168.1.xxx/admin/queries.php

**Comment by FerhatAkgun** [comment]
Getting the new update 5.0.121 beta few minutes ago via playstore, broke flutterhole for me. I tried configuring via API token or basic auth. Non of those worked. Cleared cache and reinstalled. 

The main screen/dashboard is stuck in loading.

API log just shows
GET /admin/api.php 200

**Comment by jdrch** [comment]
> 
> Getting the new update 5.0.121 beta few minutes ago via playstore, broke flutterhole for me. I tried configuring via API token or basic auth. Non of those worked. Cleared cache and reinstalled. 
> 
> The main screen/dashboard is stuck in loading.
> 
> API log just shows
> GET /admin/api.php 200

Not seeing this on my end. Make sure you clear the app data also in addition to clear the cache before you uninstall.

**Comment by FerhatAkgun** [comment]
> > Getting the new update 5.0.121 beta few minutes ago via playstore, broke flutterhole for me. I tried configuring via API token or basic auth. Non of those worked. Cleared cache and reinstalled.
> > The main screen/dashboard is stuck in loading.
> > API log just shows
> > GET /admin/api.php 200
> 
> Not seeing this on my end. Make sure you clear the app data also in addition to clear the cache before you uninstall.

I have fully cleared app data, which clears also the cache. Uninstalled it and configured it again after installing. Still same behavior.

I am using it on Android 10.
PI Hole version is 4.4
Web interface version 4.3.3
FTL version 4.3.1

I guess the new flutterhole is not backwards compatible. That should be the problem I guess.

**Comment by jdrch** [comment]
> I guess the new flutterhole is not backwards compatible. That should be the problem I guess.

The impression I get from Pi-hole v5's release notes is nothing that interacts with lists or stats is backwards compatible due to the move to a database backend. Toggle and API key functionality carry over, though.

**Comment by Anoni-Mouse** [comment]
I thought that those who didn't upgrade to pihole 5 would still have it working, but apparently it isn't. So if you leave the beta version group and revert to the October 2019 release, with your current old pihole it works right?

**Comment by FerhatAkgun** [comment]
The irritating thing is I didn't join the beta version testing in playstore at all. Something went wrong here.
Could it be possible that you have accidentally published the beta version in the stable channel?

Yesterday I had already upgraded pihole to v5. Now it works very well.

**Comment by jdrch** [comment]
@FerhatAkgun Your Pi-hole version and Flutterhole versions always need to match, otherwise you'll have problems.

If you're using Pi-hole v<5, you need stable Flutterhole. If you're using Pi-hole >=5, you need the beta Flutterhole. All other combinations have issues.

**Comment by FerhatAkgun** [comment]
> @FerhatAkgun Your Pi-hole version and Flutterhole versions always need to match, otherwise you'll have problems.
> 
> If you're using Pi-hole v<5, you need stable Flutterhole. If you're using Pi-hole >=5, you need the beta Flutterhole. All other combinations have issues.

Like I said, the mistake here is that a beta version was published in the stable channel of playstore. 
![Screenshot_20200520-120448_Google Play Store](https://user-images.githubusercontent.com/7387605/82433749-30a14700-9a92-11ea-90c3-29f894ee8239.jpg)
![Screenshot_20200520-120419_Google Play Store](https://user-images.githubusercontent.com/7387605/82433787-3b5bdc00-9a92-11ea-95f4-219c0bf6fbaa.jpg)

**Comment by sterrenburg** [comment]
> Like I said, the mistake here is that a beta version was published in the stable channel of playstore.

@FerhatAkgun indeed the play store has an old beta release, which is also made for the V5 API. The new builds are tested exclusively for V5 since I only have one Pi-hole, which I updated recently. So for now V4 is unsupported. I will update the store listing now to make this more clear, my apologies for the confusion.

**Comment by sterrenburg** [comment]
The beta build is currently equal to the production build, so I will close this issue for now.
