### ISSUE TITLE
Health Check Version Update Indication Wrong

### ISSUE THREAD

**Issue by mathmaniac43** [sterrenburg/flutterhole#72]
Hello! I love this app, and this is a minor issue I have found, so I hope it is a quick and easy fix. =)

In the Flutterhole Settings under a given Pihole configuration, clicking the Health Check drop-down queries the Pihole itself and checks the versions for Pihole, the Web Interface, and FTL.

My Pihole queried via SSH states that its versions are 4.4, 4.3.3, and 4.3.1, respectively. It also says that these are the latest versions.
```
  Pi-hole version is v4.4 (Latest: v4.4)
  AdminLTE version is v4.3.3 (Latest: v4.3.3)
  FTL version is v4.3.1 (Latest: v4.3.1)
```

Flutterhole is getting the same versions, but is indicating that the version it sees for FTL (4.3.1, which is correct) is not up-to-date, and it claims that the latest version is 4.4 (which is incorrect).

__My best guess is that there is a version check in the app that is comparing the actual FTL version to the latest known version for Pihole itself.__

**Comment by sterrenburg** [comment]
Note to self: {{ base_url  }}?versions seems to work ok on 5.0
