### ISSUE TITLE
destination pie chart colors wrong and tapping Highlights the wrong category 

### ISSUE THREAD

**Issue by andrebeekhuis** [sterrenburg/flutterhole#81]
I think the already fixed bug with tapping the pie chart query types exists with the pie chart for destination. Adding to that the pie Charts Shows other colors than the titles. 
![Screenshot_20200518-162023](https://user-images.githubusercontent.com/61388541/82223870-84d9e900-9923-11ea-8163-967a4e677677.jpg)

**Comment by sterrenburg** [comment]
Hello @andrebeekhuis 👋 - Thanks for opening an issue!

The incorrect labels in the Forward destinations chart should be fixed from version `v5.0.121` and up. If you haven't updated yet, please check the Play store. If the problem persists, please let me know!

**Comment by andrebeekhuis** [comment]
Yep, working fine!
