### ISSUE TITLE
Flutter hole shows allowed queries as blocked in v5

### ISSUE THREAD

**Issue by Stargamers** [sterrenburg/flutterhole#82]
I'm not sure if this is an App bug or an api bug but when i go to the querie log from any device the queries that are allowed are shown as blocked in the app.
Below are 2 pictures to show the problem, one is from the App and one is from the pihoe dashboard.
![Screenshot_20200518-003752](https://user-images.githubusercontent.com/12717513/82242043-77315d00-993d-11ea-8f9b-c18d86dc8674.jpg)
![flutterhole shows allowed queroes as blocked](https://user-images.githubusercontent.com/12717513/82242073-857f7900-993d-11ea-8c4c-7be3950fdc2e.png)

**Comment by sterrenburg** [comment]
Hello @Stargamers 👋 - Thanks for opening an issue!

It looks like you are correct - the status is derived from an index via the Pi-hole API ([like this](https://github.com/pi-hole/AdminLTE/blob/44aff727e59d129e6201341caa1d74c8b2954bd2/scripts/pi-hole/js/queries.js#L181)) and the app is using the wrong index.

I think I have found the culprit, expect a fix in the next release.

**Comment by Stargamers** [comment]
Hello @sterrenburg 
Latest release has fixed the bug thanks for the fast fix.
