### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by Urs1956** [sterrenburg/flutterhole#83]
Hi,
nice tool with a funny bug 151 % . See screenshot
![Screenshot_20200518-194113](https://user-images.githubusercontent.com/57187367/82243704-56b6d200-9940-11ea-9a34-a8529f545e60.png)

**Comment by sterrenburg** [comment]
Hello @Urs1956 👋 - Thanks for opening an issue!

Very interesting graph you have there. Could you try accessing the following URL in your browser:

```
{{ base_url  }}?getForwardDestinations&auth={{ auth  }}
```

An example request would look like this:

```
http://pi.hole/admin/api.php?getForwardDestinations&auth=my_token
```

You should get a JSON response looking something like this:

```json
{
  "forward_destinations": {
    "blocklist|blocklist": 24.50,
    "cache|cache": 25.50,
    "dns.google|8.8.4.4": 23.50,
    "dns.google|8.8.8.8": 26.50,
  }
}
```

 I am curious to see whether your Pi-hole has gone mad, or whether the app has.

**Comment by Urs1956** [comment]
The output is empty. I hope, the URL is correct.


![image](https://user-images.githubusercontent.com/57187367/82319554-130ca880-99d2-11ea-88cc-34b70146ba7e.png)

![image](https://user-images.githubusercontent.com/57187367/82319497-f6707080-99d1-11ea-991b-1419dfe8322c.png)

**Comment by sterrenburg** [comment]
My apologies, I should have been more clear. You have to replace `my_token` with your own API token (on the Pi-hole dashboard, under Settings > Api Web Interface > Show API token). This should result in some JSON-like response.

**Comment by Urs1956** [comment]
Here the output:

{"forward_destinations":{"blocklist|blocklist":20.97,"cache|cache":9.51,"fritz.box|fd00::3681:xxxx:yyyy:zzzz":155.15,"fritz.box|192.168.1.1":7.21}}

**Comment by sterrenburg** [comment]
Interesting, that is definitely more than 100%. What does the graph on your web dashboard show? If you hover over the pie chart in a browser, you should see some percentages too.

I just added up the values from my own Pi-hole and it adds up to 100,4%.

**Comment by Urs1956** [comment]
Sorry, at this time I havn´t hovered. I think the error is in pihole

![image](https://user-images.githubusercontent.com/57187367/82351519-f76ac780-99fc-11ea-8e59-3404b345c3d4.png)

**Comment by Urs1956** [comment]
I give this "error" to the pihole-communitiy 
https://discourse.pi-hole.net/t/summenfehler-in-darstellung/32912

**Comment by Urs1956** [comment]
The "error" is fixed: The DNS-Entries for my router was double and pihole count double this entries. After I delete one it works coreect.
In v4.x this was not a problem......

**Comment by sterrenburg** [comment]
Glad to hear you got it working!
