### ISSUE TITLE
Oneplus 7T android 10

### ISSUE THREAD

**Issue by Ryanh85** [sterrenburg/flutterhole#88]
**Describe the bug**
Running FlutterHole 5.0.125 on both Oneplus 7T Oxygen OS10.0.9.HD65AA and Fire HD 8 with Fire OS 5.6.6.0. Flutterhole works perfectly on Fire HD, but on Oneplus all i get are fetching host status failed.  The myPiHoles options are set up the same on both devices

**To Reproduce**
1. Open App
2. See error "Failure (message: pingPihole failed, error: PIExeption.malformedResponse(error:DioError[DioErrorType.DEFAULT]: SocketExeption: Failed Host Lookup: 'pi.hole' (OS Error: noaddress associated with Hostname, errno = 7)))

**Expected behavior**
Expect to see pihole on Oneplus 7T

**Screenshots**

**Versions (please complete the following information):**
 - Pi-hole version: 5.0
 - FlutterHole version: 5.0.125

**Additional context**

**Comment by Ryanh85** [comment]
OnePlus 7t 
![Screenshot_20200522-133013](https://user-images.githubusercontent.com/64654662/82694100-a9d6a080-9c30-11ea-950c-e88335a5f908.jpg)

Fire HD 
![IMG_20200522_133159](https://user-images.githubusercontent.com/64654662/82694130-b5c26280-9c30-11ea-99bb-92b56526ed1b.jpg)

**Comment by sterrenburg** [comment]
Hello @Ryanh85 👋 - Thanks for opening an issue!

Sorry to hear that. This sounds _similar_ to #86, I will give you the same tips to start off with:

- Try clearing the app data/cache from the app settings;
- Try reloading the Pi-hole configurations using the dropdown  menu on the "My Piholes" page;
- Try _deleting_ the Pi-hole configurations using the dropdown  menu on the "My Piholes" page;
- If you are using as domain in the Base URL (e.g. "http://pi.hole"), try swapping it out with the IP address (e.g. 10.0.1.2);
- Does the "API log" page show any HTTP requests being made?

Apart from that, do you know what _Android_ version your OS (Oxygen OS10.0.9) runs on?  I noticed that some Android 8.0/8.1 phones have been crashing according to the Google Play dashboard. Might be unrelated, but worth a check.

**Comment by Ryanh85** [comment]
1) cleaned app data/cache. Deleted app, reinstalled and still errors
2) reload and still errors
3) deleting And still errors
4)192.168.1.12 as IP still errors
5) 
![Screenshot_20200522-142301](https://user-images.githubusercontent.com/64654662/82697925-d5a95480-9c37-11ea-8b13-b03df8ee62d8.jpg)
![Screenshot_20200522-142306](https://user-images.githubusercontent.com/64654662/82697933-da6e0880-9c37-11ea-9477-8c8eaca784fb.jpg)
![Screenshot_20200522-142315](https://user-images.githubusercontent.com/64654662/82697941-dd68f900-9c37-11ea-8202-a42d102db496.jpg)
![Screenshot_20200522-142320](https://user-images.githubusercontent.com/64654662/82697949-e2c64380-9c37-11ea-8e45-02c2fad3322d.jpg)

**Comment by sterrenburg** [comment]
Thank you for the info. 

In the final screenshot, the Alice Error tab, the error states `Failed host lookup: 'pi.hole' ... No address associated with hostname ... `. This happens to me when the device cannot resolve `pi.hole` to the IP on my local network via DNS. Every now and again, either my Pi-hole or my device seems to forget the IP of the `pi.hole` domain. 

Could you share your logs for requests that show the Pi-hole IP in the Request error tab after "Server:"? If those requests fail as well, I assume they have another kind of error under the Alice Error tab.

**Comment by Ryanh85** [comment]
So confused. Opened flutterhole to this screen today. 
![Screenshot_20200523-080208](https://user-images.githubusercontent.com/64654662/82730245-52860e00-9ccc-11ea-8349-3b39075382c9.jpg)

So I deleted all mypihole and reloaded. Changed to IP and now it works.

![Screenshot_20200523-080539](https://user-images.githubusercontent.com/64654662/82730283-7ea18f00-9ccc-11ea-8b6b-cc1af6d82e01.jpg)

No idea what I different.

**Comment by Phrown420** [comment]
I'm getting the exact same error that Ryan had on my Oneplus 5t running android 9, tried all the tricks like reinstalling and deleting cache etc. but no dice. The API is searching for the pi.hole server even though I have it set to 192.168.1.169

**Comment by sterrenburg** [comment]
> So confused. Opened flutterhole to this screen today.

Interesting, looks like the Alice service gets passed an error that is `null`... Not sure how that happens, but glad it works again. 

Will look into better error management, the newest beta builds should have more verbose errors too.
