### ISSUE TITLE
Slight enhancements for the Beta

### ISSUE THREAD

**Issue by pchristod** [sterrenburg/flutterhole#96]
Hi, 
I'm using the current Beta with support for v5 and I think particularly the total queries section could use two enhancements if I might suggest them. 

1) support for 24h locales since 12h is not standard everywhere. Currently time is shown in 12h format.
2) like in the pi hole dashboard show the actual time when selecting a graph/point of time. Currently it's mostly guess work based on the time shown below in the graph.

In general, apart from this special section I find it also hard to navigate between points in time in that graphs because the gesture collides with the gesture to switch tabs. Often times it switches bottom tabs instead of navigating to a point of time in the graph. 

Apart from that I find the design quite beautiful and the app very handy, thank you :smile:

**Comment by sterrenburg** [comment]
Hello @pchristod 👋 - Thanks for opening an issue!

Regarding your suggestions, I made separate issues (#98 and #99 respectively).

> In general, apart from this special section I find it also hard to navigate between points in time in that graphs because the gesture collides with the gesture to switch tabs. Often times it switches bottom tabs instead of navigating to a point of time in the graph.

Regarding gestures on the dashboard, what works for me (i.e. on my own devices): if you _hold_ down for a short while (e.g. a second) on a graph, you can now slide around _without_ navigating to another subpage. The gesture detectors do fight a bit, but I am not sure what a better approach would be. Does this help you out?

**Comment by pchristod** [comment]
@sterrenburg Hey, thank you for creating those two new issues.

Your tip to hold down and then navigate is really helpful. I agree with you I would also have trouble to find a different gesture. I wrote that more to see if anyone has a good tip, and wasn't disappointed :)
